/*
 * generated by Xtext
 */
package org.xtext.example.droid.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DroidUiModule extends org.xtext.example.droid.ui.AbstractDroidUiModule {
	public DroidUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
