/*
* generated by Xtext
*/
package org.xtext.example.droid.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class DroidTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
