/*
 * generated by Xtext
 */
package org.xtext.example.droid;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DroidRuntimeModule extends org.xtext.example.droid.AbstractDroidRuntimeModule {

}
