grammar org.xtext.example.droid.Droid with org.eclipse.xtext.common.Terminals

generate droid "http://www.xtext.org/example/droid/Droid"

Application:
	'application' name=STRING
		'=>' packageName=PackageName
	(screens+=Screen | layouts+=Layout)+
;

Screen:
	'screen' name=ID
	'{'
	
	'}'
;

Layout:
	'layout' name=ID
	'{'
		views=ViewCollection
	'}'
;

ViewCollection:
	('#' views+=View)+
;

View:
	'view'
;

PackageName:
	ID ('.' ID)*
;