/*
* generated by Xtext
*/
package org.xtext.example.droid.ui.contentassist;

import org.xtext.example.droid.ui.contentassist.AbstractDroidProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class DroidProposalProvider extends AbstractDroidProposalProvider {

}
